utils::globalVariables(c("x",
                         "y",
                         ".",
                         ".data",
                         "plot.data",
                         "plot.main",
                         "plot.xlab",
                         "plot.ylab",
                         "x.data",
                         "y.data",
                         "breaks",
                         "delta.x",
                         "delta.y",
                         "x.end.first_quartile",
                         "x.normalized",
                         "x.start.fourth_quartile",
                         "y.normalized",
                         "bounds",
                         "end",
                         "fit",
                         "fit.idx",
                         "limits",
                         "norm.residual",
                         "start",
                         "otr.idx",
                         "y.fit",
                         "data.quality.check", "data.quality.check.passed.check",
                         "data.quality.passed", "data.quality.penalty", "fit.quality.penalty", "idx",
                         "mc.idx", "offset_raise.weighed", "offset_raise_required", "otr.idcs",
                         "otr.idx.end", "otr.idx.start", "pm", "quality.penalty", "range.size", "rownum", "size",
                         "weights", "x.lowerBound", "x.max", "x.min", "x.upperBound", "y.lowerBound", "y.max",
                         "y.min", "y.upperBound"))
